/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HarborRouteImport } from './routes/harbor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMatchWordRouteImport } from './routes/api/match-word'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiAlternativeDetailRouteImport } from './routes/api/alternative-detail'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HarborRoute = HarborRouteImport.update({
  id: '/harbor',
  path: '/harbor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchWordRoute = ApiMatchWordRouteImport.update({
  id: '/api/match-word',
  path: '/api/match-word',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlternativeDetailRoute = ApiAlternativeDetailRouteImport.update({
  id: '/api/alternative-detail',
  path: '/api/alternative-detail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harbor': typeof HarborRoute
  '/logs': typeof LogsRoute
  '/share': typeof ShareRoute
  '/api/alternative-detail': typeof ApiAlternativeDetailRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/match-word': typeof ApiMatchWordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harbor': typeof HarborRoute
  '/logs': typeof LogsRoute
  '/share': typeof ShareRoute
  '/api/alternative-detail': typeof ApiAlternativeDetailRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/match-word': typeof ApiMatchWordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harbor': typeof HarborRoute
  '/logs': typeof LogsRoute
  '/share': typeof ShareRoute
  '/api/alternative-detail': typeof ApiAlternativeDetailRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/match-word': typeof ApiMatchWordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/harbor'
    | '/logs'
    | '/share'
    | '/api/alternative-detail'
    | '/api/feedback'
    | '/api/match-word'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/harbor'
    | '/logs'
    | '/share'
    | '/api/alternative-detail'
    | '/api/feedback'
    | '/api/match-word'
  id:
    | '__root__'
    | '/'
    | '/harbor'
    | '/logs'
    | '/share'
    | '/api/alternative-detail'
    | '/api/feedback'
    | '/api/match-word'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HarborRoute: typeof HarborRoute
  LogsRoute: typeof LogsRoute
  ShareRoute: typeof ShareRoute
  ApiAlternativeDetailRoute: typeof ApiAlternativeDetailRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiMatchWordRoute: typeof ApiMatchWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harbor': {
      id: '/harbor'
      path: '/harbor'
      fullPath: '/harbor'
      preLoaderRoute: typeof HarborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match-word': {
      id: '/api/match-word'
      path: '/api/match-word'
      fullPath: '/api/match-word'
      preLoaderRoute: typeof ApiMatchWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alternative-detail': {
      id: '/api/alternative-detail'
      path: '/api/alternative-detail'
      fullPath: '/api/alternative-detail'
      preLoaderRoute: typeof ApiAlternativeDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HarborRoute: HarborRoute,
  LogsRoute: LogsRoute,
  ShareRoute: ShareRoute,
  ApiAlternativeDetailRoute: ApiAlternativeDetailRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiMatchWordRoute: ApiMatchWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
